name: Build Wheels

on: [push, pull_request]

jobs:
  build-wheels:
    name: Build wheels on ${{ matrix.os }} for Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, windows-2022, windows-2019]
        python-version: ['3.10', '3.11', '3.12'] # , '3.7', '3.8', '3.9']
    steps:
    - uses: actions/checkout@v2
      name: Checkout repo

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64

    - name: Change to project directory
      run: cd PyPREVENT

    - name: Install dependencies and maturin
      run: |
        python -m venv venv
        .\venv\Scripts\Activate
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install maturin twine
      shell: powershell

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    
    - name: Build with maturin
      run: |
        .\venv\Scripts\Activate
        maturin build --release --strip --out dist
      shell: powershell


    - name: Publish to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        .\venv\Scripts\Activate
        twine upload dist/* || if ($LASTEXITCODE -eq 1) { $error_message = Get-Content $env:TWINE_OUTPUT -Raw; if ($error_message -match "File already exists") { Write-Host "Package version already uploaded. Ignoring error."; exit 0 } else { exit $LASTEXITCODE } }
      shell: powershell



      


